version: '3.8'

services:
  mathoptix:
    build: .
    container_name: act_server
    ports:
      # Links ist der Port nach außen (Internet/Host), rechts der interne Container-Port
      - "7860:7860" # Streamlit Web-Interface
      - "2222:22"   # SSH-Zugang (Wir nehmen außen 2222, damit es nicht mit dem Host-SSH kollidiert)
    restart: unless-stopped
    # Optional: Wenn du live am Code arbeiten willst, ohne den Container neu zu bauen,
    # entferne die Raute (#) in den nächsten zwei Zeilen:
    # volumes:
    #   - .:/app