[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name="act"
version="0.0.1"
description="A streamlit based application to to visualize math problems."
readme="README.md"
authors=[{name="Swan"}, {name="CD"}]
keywords=[
    "act",
    ]
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
requires-python=">=3.12"

[project.urls]
Repository="https://github.com/s0kr4t3s/act.git"

[tool.setuptools]
packages = ["act"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

# ==========================================
# FORMATTER CONFIGURATION
# ==========================================
[tool.black]
line-length = 88
skip-string-normalization = true
include = '\.pyi?$'
fast = true